FinanceManager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('finance/', include('finance.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('accounts/', include('account.urls'))
]

account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
)
urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^password-change/$', PasswordChangeView.as_view(), name='password_change'),
    url(r'^password-change-done/$', PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^registration/$', views.register, name='registration')
]

finance/urls.py
from django.conf.urls import url
from django.urls import path


from . import views

app_name = 'finance'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('<int:user_id>/', views.profile, name='profile'),
    path('<int:user_id>/add_category/', views.add_category, name='add_category'),
    path('<int:user_id>/add_amount/', views.add_amount, name='add_amount')
]

account/models.py
from django.db import models

# Create your models here.

finance/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User


class Category(models.Model):
    """Категории"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="category", null=True)
    name = models.CharField("Название категория", max_length=150)
    count_amounts = 0

    def plus_amounts(self, count):
        self.count_amounts += count

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import RegisterForm


def profile(request):
    return HttpResponseRedirect('/finance')


def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/finance')
    else:
        form = RegisterForm()
    return render(response, "registration/register.html", {"form": form})

finance/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Category, User


def home(request):
    user = request.user.id
    return render(request, 'finance/home.html', {})


def profile(response, user_id):
    try:
        user = User.objects.get(id=user_id)
    except:
        raise Http404("Пользователь не найден")
    if response.user == user:
        cat_lst = Category.objects.filter(user=response.user)
        return render(response, 'finance/profile.html', {'cat_lst': cat_lst})
    return render(response, 'finance/home.html')


def add_category(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except:
        raise Http404("Пользователь не найден")
    cat = Category(user=user, name=request.POST['name'])
    cat.save()
    return HttpResponseRedirect(reverse('finance:profile', args=(user.id,)))


def add_amount(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except:
        raise Http404("Пользователь не найден")
    cat = Category.objects.get(name=request.POST['name'])
    cat.amount += request.POST['count']
    return HttpResponseRedirect(reverse('finance:profile', args=(user.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Finance Manager{% endblock %}
    </title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/finance/home.html
{% extends "base.html" %}
{% block title %}Домашняя страница{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<form>
    <input type="button" value='Сменить пароль' onClick="window.location.href = ' {% url 'password_change'%} '">
</form>
<form>
    <input type="button" value='Выйти' onClick="window.location.href = ' {% url 'logout'%} '">
</form>
<form>
    <input type="button" value='Профиль' onClick="window.location.href = ' {% url 'finance:profile' user.id%} '">
</form>
{% else%}
<form>
    <input type="button" value='войти' onClick="window.location.href = ' {% url 'login'%} '">
</form>
{% endif %}
{% endblock %}

templates/finance/profile.html
{% extends 'base.html' %}

{% block title %} {{user.username}} {% endblock %}

{%block content %}
{% for cat in cat_lst %}
<p>{{cat.name}} : {{cat.count_amounts}}</p>
{% endfor %}
<form action="{% url 'finance:add_category' user.id %}"  method = 'POST'>

    {% csrf_token %}
    <h3>Создать категорию</h3>
    <input type="text" required placeholder="Название категории", name="name"><br>
    <button type="submit">Добавить</button>

</form>
<form action="{% url 'finance:add_amount' user.id %}"  method = 'POST'>

    {% csrf_token %}
    <h3>Добавить трату</h3>
    <input type="text" required placeholder="Название категории", name="name"><br>
    <input type="number" required placeholder="Сумма", name="'count">
    <button type="submit">Добавить</button>

</form>

<form>
    <input type="button" value='Назад' onClick="window.location.href = ' {% url 'profile'%} '">
</form>
{% endblock %}